site_name: Munity documentation
nav:
    - What is Munity: index.md
    - How to start: howtostart.md
    - Customize: customize.md
    - Important files: importantfile.md
    - Manage custom content: managecustomcontent.md
    - Get help : gethelp.md
theme: readthedocs